# Generated by Django 2.0.4 on 2018-05-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FormFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_factor', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='Unknown', max_length=25)),
                ('model', models.CharField(default='Unknown', max_length=25, unique=True)),
                ('_date', models.DateField()),
                ('power', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IntelArchitecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntelGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Hardware')),
                ('status', models.CharField(default=None, max_length=255, null=True)),
                ('date', models.CharField(default=None, max_length=255, null=True)),
                ('cores', models.IntegerField(default=None, null=True)),
                ('max_clock_speed', models.FloatField(default=None, null=True)),
                ('clock_speed', models.FloatField(default=None, null=True)),
                ('cache', models.FloatField(default=None, null=True)),
                ('price', models.IntegerField(default=None, null=True)),
            ],
            bases=('catalog.hardware',),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Hardware')),
                ('volume', models.IntegerField(default=None)),
            ],
            bases=('catalog.hardware',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Hardware')),
            ],
            bases=('catalog.hardware',),
        ),
        migrations.AlterUniqueTogether(
            name='chipset',
            unique_together={('vendor', 'model')},
        ),
        migrations.CreateModel(
            name='IntelCPU',
            fields=[
                ('cpu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.CPU')),
                ('information', models.CharField(default=None, max_length=255, null=True)),
                ('architecture', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intel_cpu', to='catalog.IntelArchitecture')),
                ('codename', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intel_cpu', to='catalog.IntelGeneration')),
            ],
            bases=('catalog.cpu',),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='chipset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='catalog.Chipset'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='memory_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.MemoryType'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='socket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='catalog.Socket'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='motherboard',
            field=models.ManyToManyField(null=True, to='catalog.Motherboard'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='socket',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='catalog.Socket'),
        ),
    ]
