# Generated by Django 2.0.4 on 2018-05-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipset', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CodeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_factor', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='Unknown', max_length=25, unique=True)),
                ('_date', models.DateField()),
                ('power', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=None, null=True)),
                ('information', models.CharField(default=None, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PCSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='Unknown', max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Hardware')),
                ('status', models.CharField(default=None, max_length=255, null=True)),
                ('cores', models.IntegerField(default=None, null=True)),
                ('max_clock_speed', models.FloatField(default=None, null=True)),
                ('clock_speed', models.FloatField(default=None, null=True)),
                ('cache', models.FloatField(default=None, null=True)),
                ('architecture', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='catalog.Architecture')),
                ('codename', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='catalog.CodeName')),
                ('socket', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='catalog.Socket')),
            ],
            bases=('catalog.hardware',),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Hardware')),
                ('volume', models.IntegerField(default=None)),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.MemoryType')),
            ],
            bases=('catalog.hardware',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Hardware')),
                ('chipset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='catalog.Chipset')),
                ('form_factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.FormFactor')),
                ('memory_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.MemoryType')),
                ('socket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='catalog.Socket')),
            ],
            bases=('catalog.hardware',),
        ),
        migrations.CreateModel(
            name='PowerBlock',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Hardware')),
                ('power_capacity', models.IntegerField()),
            ],
            bases=('catalog.hardware',),
        ),
        migrations.AddField(
            model_name='hardware',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='catalog.Vendor'),
        ),
        migrations.AddField(
            model_name='pcset',
            name='cpu',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.CPU'),
        ),
        migrations.AddField(
            model_name='pcset',
            name='memory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Memory'),
        ),
        migrations.AddField(
            model_name='pcset',
            name='motherboard',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Motherboard'),
        ),
        migrations.AddField(
            model_name='pcset',
            name='power',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PowerBlock'),
        ),
        migrations.AlterUniqueTogether(
            name='pcset',
            unique_together={('cpu', 'motherboard', 'memory', 'power')},
        ),
    ]
