# Generated by Django 2.0.4 on 2018-05-16 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerBlock',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Hardware')),
                ('power_capacity', models.IntegerField()),
            ],
            bases=('catalog.hardware',),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='Unknown', max_length=25, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='chipset',
            old_name='model',
            new_name='chipset',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='motherboard',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='intelcpu',
            name='architecture',
        ),
        migrations.RemoveField(
            model_name='intelcpu',
            name='codename',
        ),
        migrations.RemoveField(
            model_name='intelcpu',
            name='information',
        ),
        migrations.AddField(
            model_name='hardware',
            name='information',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AddField(
            model_name='hardware',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='vendor',
            field=models.ForeignKey(on_delete=None, related_name='hardware', to='catalog.Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='chipset',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chipset',
            name='vendor',
        ),
        migrations.AddField(
            model_name='cpu',
            name='architecture',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='catalog.Architecture'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='codename',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='catalog.CodeName'),
        ),
    ]
