# Generated by Django 2.0.4 on 2018-06-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipset',
            name='chipset',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='socket',
            name='socket',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
