# Generated by Django 2.0.4 on 2018-05-17 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180516_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.MemoryType'),
        ),
    ]
