# Generated by Django 2.0.4 on 2018-06-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180603_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
