# Generated by Django 2.0.4 on 2018-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180603_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='information',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
